# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5c97f52307329f5fbb9f61be0ba2ed741d6267bf41dcfdd500b40d40ce96c237b9579da0742cdb79a3fb692c739143281c9b6232f0cf77ddfa5f3f8c798bc88

test:
  secret_key_base: 807c8532d301854f38e55cac15a6fa36483ebd9b1af04a8e3dc51cc83b33ce9b74febd93b4f2c0e468fdce0fd6b1cf7f911d2e68f7a0c73faa10d91883395995

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
